package trainr;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sethp
 */

import javax.swing.JOptionPane;

public class TrainRLogin extends javax.swing.JFrame {
    
    static TrainRLogin s = new TrainRLogin();

    /**
     * Creates new form TrainR
     */
    public TrainRLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogin = new javax.swing.JButton();
        lblUserLogin = new javax.swing.JLabel();
        lblPasswordLogin = new javax.swing.JLabel();
        txtPasswordLogin = new javax.swing.JTextField();
        txtUserLogin = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblUser = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        lblCreateAccount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TrainR Login");
        setBackground(new java.awt.Color(0, 0, 250));
        setName("frmLogin"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 400));
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        btnLogin.setText("Login");
        btnLogin.setName("btnLogin"); // NOI18N
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(477, 160, 70, 21);

        lblUserLogin.setText("Username: ");
        lblUserLogin.setName("lblUserLogin"); // NOI18N
        getContentPane().add(lblUserLogin);
        lblUserLogin.setBounds(310, 50, 70, 13);

        lblPasswordLogin.setText("Password: ");
        lblPasswordLogin.setName("lblPasswordLogin"); // NOI18N
        getContentPane().add(lblPasswordLogin);
        lblPasswordLogin.setBounds(310, 100, 70, 13);

        txtPasswordLogin.setFont(new java.awt.Font("Symbol", 0, 10)); // NOI18N
        txtPasswordLogin.setName("txtPasswordLogin"); // NOI18N
        txtPasswordLogin.setNextFocusableComponent(btnLogin);
        getContentPane().add(txtPasswordLogin);
        txtPasswordLogin.setBounds(400, 100, 150, 30);

        txtUserLogin.setName("txtUserLogin"); // NOI18N
        txtUserLogin.setNextFocusableComponent(lblPasswordLogin);
        getContentPane().add(txtUserLogin);
        txtUserLogin.setBounds(400, 50, 100, 30);

        btnSubmit.setText("Submit");
        btnSubmit.setName("btnSubmit"); // NOI18N
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit);
        btnSubmit.setBounds(160, 250, 90, 21);

        lblName.setText("Full Name: ");
        lblName.setName("lblName"); // NOI18N
        getContentPane().add(lblName);
        lblName.setBounds(10, 50, 70, 13);

        lblLogin.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblLogin.setText("Login");
        lblLogin.setToolTipText("");
        lblLogin.setName("lblLogin"); // NOI18N
        getContentPane().add(lblLogin);
        lblLogin.setBounds(310, 10, 30, 13);

        txtName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtName.setMaximumSize(new java.awt.Dimension(50, 50));
        txtName.setMinimumSize(new java.awt.Dimension(1, 1));
        txtName.setName("txtName"); // NOI18N
        txtName.setNextFocusableComponent(lblEmail);
        txtName.setPreferredSize(new java.awt.Dimension(7, 25));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName);
        txtName.setBounds(100, 50, 100, 30);

        lblEmail.setText("Email: ");
        lblEmail.setName("lblEmail"); // NOI18N
        getContentPane().add(lblEmail);
        lblEmail.setBounds(10, 100, 40, 13);

        txtEmail.setName("txtEmail"); // NOI18N
        txtEmail.setNextFocusableComponent(lblUser);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail);
        txtEmail.setBounds(100, 100, 150, 30);

        lblUser.setText("Username: ");
        lblUser.setName("lblUser"); // NOI18N
        getContentPane().add(lblUser);
        lblUser.setBounds(10, 150, 70, 13);

        lblPassword.setText("Password: ");
        lblPassword.setName("lblPassword"); // NOI18N
        getContentPane().add(lblPassword);
        lblPassword.setBounds(10, 200, 70, 13);

        txtPassword.setFont(new java.awt.Font("Symbol", 0, 10)); // NOI18N
        txtPassword.setName("txtPassword"); // NOI18N
        txtPassword.setNextFocusableComponent(btnSubmit);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword);
        txtPassword.setBounds(100, 200, 150, 30);

        txtUser.setName("txtUser"); // NOI18N
        txtUser.setNextFocusableComponent(lblPassword);
        getContentPane().add(txtUser);
        txtUser.setBounds(100, 150, 100, 30);

        lblCreateAccount.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblCreateAccount.setText("Create Account");
        lblCreateAccount.setToolTipText("");
        lblCreateAccount.setName("lblCreateAccount"); // NOI18N
        getContentPane().add(lblCreateAccount);
        lblCreateAccount.setBounds(10, 10, 90, 13);

        getAccessibleContext().setAccessibleName("frmLogin");
        getAccessibleContext().setAccessibleDescription("");
        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if(!txtUser.getText().matches("^[a-zA-Z0-9]{6,15}$")){
            JOptionPane.showMessageDialog(null,
                    "Please enter a valid username!");
        } if(!txtPassword.getText().matches("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])"
                + "(?=.*[@#$%^&+=!])(?=\\S+$).{8,15}$")){
            JOptionPane.showMessageDialog(null,
                    "Please enter a valid password!");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        boolean error = false;
        if(!txtName.getText().matches("^[a-zA-Z ]*{4,50}$")){
            JOptionPane.showMessageDialog(null,
                    "Please enter a valid name!");
            error = true;
        }else if(!txtEmail.getText().matches("^[a-zA-Z0-9_+&*-]+(?:\\."+ 
                            "[a-zA-Z0-9_+&*-]+)*@" + 
                            "(?:[a-zA-Z0-9-]+\\.)+[a-z" + 
                            "A-Z]{2,40}$")){
            JOptionPane.showMessageDialog(null,
                    "Please enter a valid email!");
            error = true;
        }else if(!txtUser.getText().matches("^[a-zA-Z0-9]{6,15}$")){
            JOptionPane.showMessageDialog(null,
                    "Please enter a valid username!");
            error = true;
        }else if(!txtPassword.getText().matches("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])"
                + "(?=.*[@#$%^&+=!])(?=\\S+$).{8,15}$")){
            JOptionPane.showMessageDialog(null,
                    "Please enter a valid password!");
            error = true;
        }else {
            error = false;
        }
        if (error == false){
            s.dispose();
            TrainRHome m = new TrainRHome();
            m.setVisible(true);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        //TODO
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainRLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainRLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainRLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainRLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                s.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblCreateAccount;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordLogin;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUserLogin;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPasswordLogin;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtUserLogin;
    // End of variables declaration//GEN-END:variables
}
